# src/pdftl/operations/update_bookmarks.py

"""Update PDF Table of Contents from a YAML or JSON file."""

import json
import logging

import pdftl.core.constants as c
from pdftl.core.core_types import OpResult
from pdftl.core.registry import register_operation
from pdftl.exceptions import MissingArgumentError, OperationError
from pdftl.info.toc import build_toc_tree
from pdftl.utils.dependencies import ensure_dependencies
from pdftl.utils.io_helpers import smart_open

logger = logging.getLogger(__name__)

_UPDATE_TOC_LONG_DESC = """Replaces the document's Table of Contents
(bookmarks) entirely using a specified YAML or JSON file, or YAML data
on stdin if `bookmarks_file` is set to "`-`".

This operation consumes the structured format generated by the
`dump_bookmarks` command. It applies strict validation to prevent broken
PDFs: it validates page boundaries, catches typos in property names,
and ensures the hierarchical tree structure is sound.

### Important Rules & Behaviors
* **Full Replacement:** This command does not merge or append bookmarks. It completely
  overwrites the existing Table of Contents with the contents of your file.
* **Page Indexing:** Target `page` numbers must be 1-indexed (e.g., `page: 1`
  points to the very first physical page of the document).
* **Boundary Checking:** If a bookmark points to a page number that exceeds
  the total number of pages in the PDF, the operation will fail safely to
  prevent document corruption.
* **Strict Validation:** Unrecognized properties (such as a typoed `pagee` instead
  of `page`) will trigger an error rather than being silently ignored. This ensures
  your routing logic always behaves as expected.

### Clearing Bookmarks
If you want to completely remove the Table of Contents from a PDF, you
can provide a file containing just an empty list.
* **YAML file content:** `[]`
* **JSON file content:** `[]`

### Dependency note
Loading YAML files requires the `pyyaml` library. If it is not installed,
you can install it via `pip install pdftl[yaml-bookmarks]`, or simply use
`.json` files natively.
"""

_UPDATE_TOC_EXAMPLES = [
    {
        "desc": "Apply a YAML bookmarks file",
        "cmd": "in.pdf update_bookmarks bookmarks.yaml output modified.pdf",
    },
    {
        "desc": "Apply a JSON bookmarks file",
        "cmd": "in.pdf update_bookmarks bookmarks.json output modified.pdf",
    },
]


@register_operation(
    "update_bookmarks",
    tags=["info", "metadata", "bookmarks"],
    type="single input operation",
    desc="Replace PDF bookmarks from a YAML or JSON file",
    long_desc=_UPDATE_TOC_LONG_DESC,
    examples=_UPDATE_TOC_EXAMPLES,
    usage="<input> update_bookmarks <bookmarks_file> output <filename>",
    args=([c.INPUT_PDF, c.OPERATION_ARGS], {}),
)
def update_toc(pdf, op_args) -> OpResult:
    file_path, is_yaml, is_json = _get_file_traits(op_args)
    yaml_module = _try_import_yaml(is_yaml)

    with smart_open(file_path, mode="r") as f:
        content = f.read()

    toc_items, parsers_tried, errors = _parse_content(content, is_json, is_yaml, yaml_module)

    if toc_items is None:
        _handle_parse_failure(content, file_path, yaml_module, errors, parsers_tried)

    _validate_toc_structure(toc_items)
    logger.debug("Got %s items for the new toc tree", len(toc_items))

    _apply_toc_tree(pdf, toc_items)
    return OpResult(success=True, pdf=pdf)


def _get_file_traits(op_args):
    """Validate operational arguments and discover file type intentions."""
    if not op_args:
        raise MissingArgumentError("update_bookmarks requires a <bookmarks_file> argument")

    file_path = op_args[0]
    if file_path == "-":
        file_path = None

    is_yaml = file_path is not None and file_path.lower().endswith((".yaml", ".yml"))
    is_json = file_path is not None and file_path.lower().endswith(".json")
    return file_path, is_yaml, is_json


def _try_import_yaml(is_yaml_ext: bool):
    """Attempt parsing library extraction, ensuring explicit path rules are hit."""
    try:
        import yaml

        return yaml
    except ImportError:
        logger.debug("No YAML support")
        if is_yaml_ext:
            _ensure_yaml_or_raise()
        return None


def _ensure_yaml_or_raise():
    ensure_dependencies(
        feature_name="YAML bookmarks loading",
        dependencies={"yaml": "pyyaml"},
        extra_tag="yaml",
    )


def _try_parse_json(content: str, is_json_ext: bool):
    """Isolated handling of standard JSON library conversions."""
    try:
        return json.loads(content), None
    except json.JSONDecodeError as exc:
        if is_json_ext:
            raise OperationError(f"Failed to parse JSON file: {exc}") from exc
        return None, exc


def _try_parse_yaml(content: str, is_yaml_ext: bool, yaml_module):
    """Isolated handling of third-party YAML library conversions."""
    try:
        return yaml_module.safe_load(content), None
    except yaml_module.YAMLError as exc:
        if is_yaml_ext:
            raise OperationError(f"Failed to parse YAML file: {exc}") from exc
        return None, exc


def _parse_content(content: str, is_json: bool, is_yaml: bool, yaml_module):
    """Determine runtime parser order sequences and catch execution exceptions."""
    toc_items = None
    parsers_tried = []
    errors = {}

    if not is_yaml:
        parsers_tried.append("json")
        toc_items, json_exc = _try_parse_json(content, is_json)
        if json_exc:
            errors["json"] = json_exc

    if toc_items is None and yaml_module is not None:
        parsers_tried.append("yaml")
        toc_items, yaml_exc = _try_parse_yaml(content, is_yaml, yaml_module)
        if yaml_exc:
            errors["yaml"] = yaml_exc

    return toc_items, parsers_tried, errors


def _handle_parse_failure(content: str, file_path, yaml_module, errors, parsers_tried):
    """Process contextual edge cases for stream failures and invalid strings."""
    if file_path is None and yaml_module is None:
        if content.strip().startswith(("[", "{")):
            json_err = errors.get("json", "Unknown JSON error")
            raise OperationError(f"Invalid JSON data provided on stdin: {json_err}")

        _ensure_yaml_or_raise()

    error_msgs = ", ".join([f"{k}: {v}" for k, v in errors.items()])
    raise OperationError(
        f"Could not parse bookmarks input. Parsers tried: {parsers_tried}. Details: {error_msgs}"
    )


def _validate_toc_structure(toc_items):
    """Ensure the underlying structure matches our required target types."""
    if not isinstance(toc_items, list):
        raise OperationError(
            "Invalid bookmarks format: Root element must be a list of items."
            " To delete all bookmarks, use []."
        )


def _apply_toc_tree(pdf, toc_items):
    """Final structural interface to apply the TOC items onto our PDF asset."""
    try:
        build_toc_tree(pdf, toc_items)
    except ValueError as exc:
        raise OperationError(exc) from exc
