name: Test MacPorts Build

on:
  push:
    paths:
      - 'macports/Portfile'
      - '.github/workflows/macports.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-on-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup MacPorts
        uses: melusina-org/setup-macports@v1

      - name: Build and Install pdftl
        run: |
          echo "Setting up official MacPorts Local Repository..."

          # 1. Create the standard MacPorts directory structure
          LOCAL_REPO="/opt/local/var/macports/sources/local"
          PORT_DIR="$LOCAL_REPO/python/pdftl"
          sudo mkdir -p "$PORT_DIR"

          # 2. Copy the Portfile from your git repo into the MacPorts system
          echo "__________ Portfile contents: __________"
          sudo cat macports/Portfile
          echo "________________________________________"
          sudo cp macports/Portfile "$PORT_DIR/"

          # 3. Create the port index so MacPorts adds it to its internal database
          cd "$LOCAL_REPO"
          sudo portindex

          # 4. Register the local repo in MacPorts sources.conf
          # We prepend it to the file so MacPorts checks our local repo first
          echo "file://$LOCAL_REPO" > /tmp/sources.conf
          cat /opt/local/etc/macports/sources.conf >> /tmp/sources.conf
          sudo mv /tmp/sources.conf /opt/local/etc/macports/sources.conf

          echo "Running which, then uninstalling, and trying again"
          which pdftl || echo pdftl not found
          which pdftl-3.12 || echo pdftl-3.12 not found
          which pdftl-3.13 || echo pdftl-3.13 not found
          which pdftl-3.14 || echo pdftl-3.14 not found
          sudo port uninstall pdftl || true
          sudo port uninstall py312-pdftl || true
          sudo port uninstall py313-pdftl || true
          sudo port uninstall py314-pdftl || true
          which pdftl || echo pdftl not found
          which pdftl-3.12 || echo pdftl-3.12 not found
          which pdftl-3.13 || echo pdftl-3.13 not found
          which pdftl-3.14 || echo pdftl-3.14 not found

          echo "searching for setuptools_scm"
          port search setuptools_scm || true

          # fix missing macports user issue
          echo "macportsuser root" | sudo tee -a /opt/local/etc/macports/macports.conf

          echo "Starting MacPorts installation test..."

          # 5. Because it's indexed globally, we can use the standard install command!
          sudo port selfupdate
          sudo port -v install pdftl

          echo "Installation successful! Testing CLI execution..."
          port contents pdftl

          # Verify the executable is in the PATH
          pdftl --help
          pdftl cat --help
          pdftl --version

      - name: Show MacPorts log on failure
        if: failure()
        run: cat /opt/local/var/macports/logs/_opt_local_var_macports_sources_local_python_pdftl/pdftl/main.log
